[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"

remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"
